# Generated by Django 3.2.4 on 2021-06-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.BinaryField(verbose_name='Изображение в формате BLOB')),
                ('pic_name', models.CharField(max_length=50, verbose_name='Название изображения')),
            ],
        ),
    ]
