# Generated by Django 3.2.4 on 2021-06-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='pic',
        ),
    ]
