# Generated by Django 3.2.4 on 2021-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0002_remove_pic_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='pic',
            field=models.ImageField(default='Suck my Dick', upload_to=''),
        ),
        migrations.AddField(
            model_name='pic',
            name='url',
            field=models.URLField(default='Suck my Dick Too', max_length=30, verbose_name='URL ссылка на изображение'),
        ),
    ]
