# Generated by Django 3.2.4 on 2021-06-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0004_auto_20210610_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='url',
            field=models.URLField(default='Введите ссылку', max_length=30, verbose_name='URL ссылка на изображение'),
        ),
    ]
