# Generated by Django 3.2.4 on 2021-06-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0008_auto_20210610_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='url',
            field=models.URLField(default='', verbose_name='URL ссылка на изображение'),
        ),
    ]
