# Generated by Django 3.2.4 on 2021-06-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0010_alter_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='pic',
        ),
        migrations.AlterField(
            model_name='pic',
            name='url',
            field=models.CharField(max_length=300, verbose_name='URL ссылка на изображение'),
        ),
    ]
