# Generated by Django 3.2.4 on 2021-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0011_auto_20210610_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
