# Generated by Django 3.2.4 on 2021-06-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0013_remove_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='url',
            field=models.URLField(default='', max_length=300, verbose_name='URL ссылка на изображение'),
        ),
    ]
