# Generated by Django 3.2.4 on 2021-06-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0015_auto_20210610_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='pic_name',
            field=models.CharField(default='None', max_length=50, null=True, verbose_name='Название изображения'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='url',
            field=models.URLField(default='None', max_length=300, null=True, verbose_name='URL ссылка на изображение'),
        ),
    ]
