# Generated by Django 3.2.4 on 2021-06-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0017_auto_20210610_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
