# Generated by Django 3.2.4 on 2021-06-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0019_alter_pic_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='pic_name',
            new_name='name',
        ),
    ]
