# Generated by Django 3.2.4 on 2021-06-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0020_rename_pic_name_pic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='pic',
            field=models.CharField(max_length=50, null=True, verbose_name='Путь до изображения'),
        ),
    ]
