# Generated by Django 3.2.4 on 2021-06-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0021_alter_pic_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pic',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
