# Generated by Django 3.2.4 on 2021-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0022_auto_20210610_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pic',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
